<?php
namespace app\modules\admin\controllers;

use app\modules\common\controllers\BaseAdminController;
use yii\web\Controller;
/**
 * Default controller for the `Module` module
 */
class DefaultController extends Controller
{

    function beforeAction($action)
    {
        var_dump($action->id);
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * Renders the index view for the module
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
}
